package config

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

// EnvConfig holds values from /etc/default/mavlink-router.
type EnvConfig struct {
	InputType    string `json:"inputType"`
	UartDevice   string `json:"uartDevice"`
	UartBaud     string `json:"uartBaud"`
	InputAddress string `json:"inputAddress"`
	InputPort    string `json:"inputPort"`
	UdpEndpoints string `json:"udpEndpoints"`
}

// ParseEnvFile reads the mavlink-router environment file.
func ParseEnvFile(path string) (*EnvConfig, error) {
	f, err := os.Open(path)
	if err != nil {
		return &EnvConfig{}, nil // Return empty if not found
	}
	defer f.Close()

	env := &EnvConfig{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eqIdx := strings.IndexByte(line, '=')
		if eqIdx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eqIdx])
		val := strings.Trim(strings.TrimSpace(line[eqIdx+1:]), "\"")

		switch key {
		case "INPUT_TYPE":
			env.InputType = val
		case "UART_DEVICE":
			env.UartDevice = val
		case "UART_BAUD":
			env.UartBaud = val
		case "INPUT_ADDRESS":
			env.InputAddress = val
		case "INPUT_PORT":
			env.InputPort = val
		case "UDP_ENDPOINTS":
			env.UdpEndpoints = val
		}
	}
	return env, nil
}

// EnvFromConfig derives the companion env file values from the parsed router config.
func EnvFromConfig(pc *ParsedConfig) *EnvConfig {
	env := &EnvConfig{}
	if pc == nil {
		return env
	}

	udpEndpoints := make([]string, 0)
	for _, ep := range pc.Endpoints {
		if !ep.Enabled {
			continue
		}
		switch ep.Type {
		case "UartEndpoint":
			env.InputType = "uart"
			env.UartDevice = ep.Device
			if ep.Baud > 0 {
				env.UartBaud = strconv.Itoa(ep.Baud)
			}
		case "UdpEndpoint":
			if strings.EqualFold(ep.Mode, "server") && ep.Name == "input" {
				env.InputType = "udp"
				env.InputAddress = ep.Address
				if ep.Port > 0 {
					env.InputPort = strconv.Itoa(ep.Port)
				}
				continue
			}
			if !strings.EqualFold(ep.Mode, "server") && ep.Address != "" && ep.Port > 0 {
				udpEndpoints = append(udpEndpoints, fmt.Sprintf("%s:%d", ep.Address, ep.Port))
			}
		}
	}

	sort.Strings(udpEndpoints)
	env.UdpEndpoints = strings.Join(udpEndpoints, ",")
	return env
}

// WriteEnvFile writes the minimal dashboard-compatible env file.
func WriteEnvFile(path string, env *EnvConfig) error {
	if env == nil {
		env = &EnvConfig{}
	}

	var b strings.Builder
	b.WriteString("# Generated by mavlink-anywhere dashboard\n")
	writeEnvLine := func(key, value string) {
		if value == "" {
			b.WriteString(fmt.Sprintf("%s=\"\"\n", key))
			return
		}
		b.WriteString(fmt.Sprintf("%s=\"%s\"\n", key, value))
	}

	writeEnvLine("INPUT_TYPE", env.InputType)
	writeEnvLine("UART_DEVICE", env.UartDevice)
	writeEnvLine("UART_BAUD", env.UartBaud)
	writeEnvLine("INPUT_ADDRESS", env.InputAddress)
	writeEnvLine("INPUT_PORT", env.InputPort)
	writeEnvLine("UDP_ENDPOINTS", env.UdpEndpoints)

	return os.WriteFile(path, []byte(b.String()), 0644)
}

// SyncEnvFromConfig regenerates the environment file from the current config.
func SyncEnvFromConfig(configPath, envPath string) error {
	pc, err := ParseConfigFile(configPath)
	if err != nil {
		return err
	}
	return WriteEnvFile(envPath, EnvFromConfig(pc))
}
