package config

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/alireza787b/mavlink-anywhere/dashboard/internal/endpoints"
)

// ParsedConfig represents the full mavlink-router configuration.
type ParsedConfig struct {
	General    GeneralSection       `json:"general"`
	Endpoints  []endpoints.Endpoint `json:"endpoints"`
	Raw        string               `json:"raw"`
	ModifiedAt time.Time            `json:"modifiedAt"`
}

// GeneralSection holds [General] section values.
type GeneralSection struct {
	TcpServerPort int  `json:"tcpServerPort"`
	ReportStats   bool `json:"reportStats"`
}

// ParseConfigFile reads and parses an INI-style mavlink-router config file.
func ParseConfigFile(path string) (*ParsedConfig, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("stat config: %w", err)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}

	return ParseConfigText(string(raw), info.ModTime())
}

// ParseConfigText parses an INI-style mavlink-router config string.
func ParseConfigText(raw string, modifiedAt time.Time) (*ParsedConfig, error) {
	pc := &ParsedConfig{
		General: GeneralSection{
			TcpServerPort: 5760,
		},
		Raw:        raw,
		ModifiedAt: modifiedAt,
	}

	scanner := bufio.NewScanner(strings.NewReader(raw))

	var currentSection string
	var currentName string
	var currentType string
	props := map[string]string{}

	flushEndpoint := func() {
		if currentType == "" || currentName == "" {
			return
		}
		ep := buildEndpoint(currentType, currentName, props)
		pc.Endpoints = append(pc.Endpoints, ep)
	}

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			// Flush previous endpoint
			if currentSection != "General" {
				flushEndpoint()
			}
			props = map[string]string{}

			section := line[1 : len(line)-1]
			parts := strings.SplitN(section, " ", 2)
			currentSection = parts[0]
			currentName = ""
			currentType = ""
			if len(parts) > 1 {
				currentName = parts[1]
			}

			switch {
			case currentSection == "General":
				// handled below
			case strings.HasPrefix(currentSection, "UdpEndpoint"):
				currentType = "UdpEndpoint"
				if currentName == "" {
					currentName = currentSection
				}
			case strings.HasPrefix(currentSection, "UartEndpoint"):
				currentType = "UartEndpoint"
				if currentName == "" {
					currentName = currentSection
				}
			case strings.HasPrefix(currentSection, "TcpEndpoint"):
				currentType = "TcpEndpoint"
				if currentName == "" {
					currentName = currentSection
				}
			}
			continue
		}

		// Key=Value
		eqIdx := strings.IndexByte(line, '=')
		if eqIdx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eqIdx])
		val := strings.TrimSpace(line[eqIdx+1:])

		if currentSection == "General" {
			switch key {
			case "TcpServerPort":
				if v, err := strconv.Atoi(val); err == nil {
					pc.General.TcpServerPort = v
				}
			case "ReportStats":
				pc.General.ReportStats = strings.EqualFold(val, "true")
			}
		} else {
			props[key] = val
		}
	}

	// Flush last section
	flushEndpoint()

	return pc, nil
}

func buildEndpoint(epType, name string, props map[string]string) endpoints.Endpoint {
	ep := endpoints.Endpoint{
		Name:    name,
		Type:    epType,
		Enabled: true,
	}

	switch epType {
	case "UartEndpoint":
		ep.Device = props["Device"]
		ep.Baud, _ = strconv.Atoi(props["Baud"])
		ep.Category = "input"
		ep.Description = "Serial connection to flight controller"
		ep.Removable = false

	case "UdpEndpoint":
		ep.Mode = strings.ToLower(props["Mode"])
		if ep.Mode == "" {
			ep.Mode = "normal"
		}
		ep.Address = props["Address"]
		ep.Port, _ = strconv.Atoi(props["Port"])
		ep.Description = endpoints.DescriptionForEndpoint(name, ep.Mode, ep.Address, ep.Port)
		ep.Category = endpoints.CategoryForEndpoint(name, ep.Mode, ep.Address, ep.Port)
		ep.Removable = true

	case "TcpEndpoint":
		ep.Address = props["Address"]
		ep.Port, _ = strconv.Atoi(props["Port"])
		ep.Category = "custom"
		ep.Description = "TCP endpoint"
		ep.Removable = true
	}

	return ep
}

// WriteConfigFile writes a full INI config file preserving the mavlink-router format.
func WriteConfigFile(path string, pc *ParsedConfig) error {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# MAVLink Router Configuration\n"))
	b.WriteString(fmt.Sprintf("# Generated by mavlink-anywhere dashboard at %s\n\n", time.Now().Format(time.RFC3339)))

	// [General]
	b.WriteString("[General]\n")
	b.WriteString(fmt.Sprintf("TcpServerPort=%d\n", pc.General.TcpServerPort))
	b.WriteString(fmt.Sprintf("ReportStats=%s\n", strconv.FormatBool(pc.General.ReportStats)))
	b.WriteString("\n")

	// Endpoints
	for _, ep := range pc.Endpoints {
		if !ep.Enabled {
			b.WriteString(fmt.Sprintf("# Disabled: %s\n", ep.Name))
			continue
		}
		switch ep.Type {
		case "UartEndpoint":
			b.WriteString(fmt.Sprintf("[UartEndpoint %s]\n", ep.Name))
			b.WriteString(fmt.Sprintf("Device=%s\n", ep.Device))
			b.WriteString(fmt.Sprintf("Baud=%d\n", ep.Baud))
		case "UdpEndpoint":
			b.WriteString(fmt.Sprintf("[UdpEndpoint %s]\n", ep.Name))
			b.WriteString(fmt.Sprintf("Mode=%s\n", ep.Mode))
			b.WriteString(fmt.Sprintf("Address=%s\n", ep.Address))
			b.WriteString(fmt.Sprintf("Port=%d\n", ep.Port))
		case "TcpEndpoint":
			b.WriteString(fmt.Sprintf("[TcpEndpoint %s]\n", ep.Name))
			b.WriteString(fmt.Sprintf("Address=%s\n", ep.Address))
			b.WriteString(fmt.Sprintf("Port=%d\n", ep.Port))
		}
		b.WriteString("\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

// WriteConfigAndEnv writes the config file and regenerates the companion env file.
func WriteConfigAndEnv(configPath, envPath string, pc *ParsedConfig) error {
	if err := WriteConfigFile(configPath, pc); err != nil {
		return err
	}
	return WriteEnvFile(envPath, EnvFromConfig(pc))
}

// WriteRawConfig validates and writes raw config text, then regenerates the env file.
func WriteRawConfig(configPath, envPath, raw string) error {
	pc, err := ParseConfigText(raw, time.Now())
	if err != nil {
		return err
	}
	return WriteConfigAndEnv(configPath, envPath, pc)
}

// ConfigModTime returns the modification time of the config file.
func ConfigModTime(path string) (time.Time, error) {
	info, err := os.Stat(path)
	if err != nil {
		return time.Time{}, err
	}
	return info.ModTime(), nil
}

// AddEndpoint adds a new endpoint to a parsed config and writes it.
func AddEndpoint(path string, ep endpoints.Endpoint) error {
	pc, err := ParseConfigFile(path)
	if err != nil {
		return err
	}

	// Check for name conflict
	for _, existing := range pc.Endpoints {
		if existing.Name == ep.Name {
			return fmt.Errorf("endpoint %q already exists", ep.Name)
		}
	}
	if err := ValidateEndpointTopology(pc.Endpoints, ep, ""); err != nil {
		return err
	}

	ep.Enabled = true
	pc.Endpoints = append(pc.Endpoints, ep)
	return WriteConfigFile(path, pc)
}

// UpdateEndpoint replaces an endpoint by name.
func UpdateEndpoint(path string, name string, ep endpoints.Endpoint) error {
	pc, err := ParseConfigFile(path)
	if err != nil {
		return err
	}

	found := false
	for i, existing := range pc.Endpoints {
		if existing.Name == name {
			ep.Type = existing.Type
			if ep.Type == "" {
				ep.Type = "UdpEndpoint"
			}
			if err := ValidateEndpointTopology(pc.Endpoints, ep, name); err != nil {
				return err
			}
			pc.Endpoints[i] = ep
			found = true
			break
		}
	}
	if !found {
		return fmt.Errorf("endpoint %q not found", name)
	}

	return WriteConfigFile(path, pc)
}

// DeleteEndpoint removes an endpoint by name.
func DeleteEndpoint(path, name string) error {
	pc, err := ParseConfigFile(path)
	if err != nil {
		return err
	}

	newEps := make([]endpoints.Endpoint, 0, len(pc.Endpoints))
	found := false
	for _, ep := range pc.Endpoints {
		if ep.Name == name {
			found = true
			continue
		}
		newEps = append(newEps, ep)
	}
	if !found {
		return fmt.Errorf("endpoint %q not found", name)
	}

	pc.Endpoints = newEps
	return WriteConfigFile(path, pc)
}

// ToggleEndpoint enables or disables an endpoint by name.
func ToggleEndpoint(path, name string, enabled bool) error {
	pc, err := ParseConfigFile(path)
	if err != nil {
		return err
	}

	found := false
	for i, ep := range pc.Endpoints {
		if ep.Name == name {
			pc.Endpoints[i].Enabled = enabled
			found = true
			break
		}
	}
	if !found {
		return fmt.Errorf("endpoint %q not found", name)
	}

	return WriteConfigFile(path, pc)
}
