#!/bin/bash
# =============================================================================
# MAVLink-Anywhere Library: Configuration Generation
# =============================================================================
# Version: 2.0.0
# Description: Generate mavlink-router configuration files
# Author: Alireza Ghaderi
# GitHub: https://github.com/alireza787b/mavlink-anywhere
# =============================================================================

# Prevent double-sourcing
[[ -n "${_MAVLINK_CONFIG_LOADED:-}" ]] && return 0
_MAVLINK_CONFIG_LOADED=1

# Source common library if not already loaded
if [[ -z "${_MAVLINK_COMMON_LOADED:-}" ]]; then
    source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
fi

# =============================================================================
# CONFIGURATION FILE GENERATION
# =============================================================================

# Generate main.conf header section
generate_config_header() {
    cat <<EOF
# =============================================================================
# MAVLink Router Configuration
# Generated by mavlink-anywhere v${MAVLINK_ANYWHERE_VERSION}
# Generated at: $(date -Iseconds)
# =============================================================================

[General]
TcpServerPort=5760
ReportStats=false

EOF
}

# Generate UART endpoint section
generate_uart_endpoint() {
    local device="$1"
    local baud="$2"
    local name="${3:-uart}"

    cat <<EOF
[UartEndpoint ${name}]
Device=${device}
Baud=${baud}

EOF
}

# Generate UDP endpoint section (outbound - normal mode)
generate_udp_endpoint() {
    local address="$1"
    local port="$2"
    local name="$3"
    local mode="${4:-normal}"

    cat <<EOF
[UdpEndpoint ${name}]
Mode=${mode}
Address=${address}
Port=${port}

EOF
}

# Generate UDP server endpoint section (inbound - server mode)
generate_udp_server_endpoint() {
    local address="$1"
    local port="$2"
    local name="${3:-udp_input}"

    cat <<EOF
[UdpEndpoint ${name}]
Mode=server
Address=${address}
Port=${port}

EOF
}

# Parse endpoint string and generate appropriate config section
# Supports formats: IP:PORT or named shortcuts
parse_and_generate_endpoint() {
    local endpoint="$1"
    local index="$2"

    # Handle named shortcuts
    case "$endpoint" in
        mavsdk|MAVSDK)
            generate_udp_endpoint "127.0.0.1" "14540" "mavsdk"
            return
            ;;
        mavlink2rest|MAVLINK2REST)
            generate_udp_endpoint "127.0.0.1" "14569" "mavlink2rest"
            return
            ;;
        local|LOCAL)
            generate_udp_endpoint "127.0.0.1" "12550" "local_mavlink"
            return
            ;;
    esac

    # Parse IP:PORT format
    if [[ "$endpoint" =~ ^([^:]+):([0-9]+)$ ]]; then
        local address="${BASH_REMATCH[1]}"
        local port="${BASH_REMATCH[2]}"
        local name="udp${index}"

        # Use descriptive names for well-known ports
        case "$port" in
            14540) name="mavsdk" ;;
            14550) name="gcs" ;;
            14569) name="mavlink2rest" ;;
            12550) name="local_mavlink" ;;
            24550) name="gcs_vpn" ;;
            34550) name="aggregation" ;;
        esac

        generate_udp_endpoint "$address" "$port" "$name"
    else
        ma_log_warn "Invalid endpoint format: $endpoint (expected IP:PORT)"
    fi
}

# Generate complete configuration for UART input
generate_uart_config() {
    local uart_device="$1"
    local uart_baud="$2"
    local endpoints="$3"  # Comma-separated list

    local config=""

    # Header
    config+=$(generate_config_header)

    # UART endpoint
    config+=$(generate_uart_endpoint "$uart_device" "$uart_baud")

    # Parse and add UDP endpoints
    local endpoint_array
    IFS=',' read -ra endpoint_array <<< "$endpoints"

    local index=1
    for endpoint in "${endpoint_array[@]}"; do
        endpoint=$(echo "$endpoint" | tr -d ' ')  # Trim whitespace
        if [[ -n "$endpoint" ]]; then
            config+=$(parse_and_generate_endpoint "$endpoint" "$index")
            ((index++))
        fi
    done

    echo "$config"
}

# Generate complete configuration for UDP input
generate_udp_input_config() {
    local input_address="$1"
    local input_port="$2"
    local endpoints="$3"  # Comma-separated list

    local config=""

    # Header
    config+=$(generate_config_header)

    # UDP input (server mode)
    config+=$(generate_udp_server_endpoint "$input_address" "$input_port" "input")

    # Parse and add output UDP endpoints
    local endpoint_array
    IFS=',' read -ra endpoint_array <<< "$endpoints"

    local index=1
    for endpoint in "${endpoint_array[@]}"; do
        endpoint=$(echo "$endpoint" | tr -d ' ')  # Trim whitespace
        if [[ -n "$endpoint" ]]; then
            config+=$(parse_and_generate_endpoint "$endpoint" "$index")
            ((index++))
        fi
    done

    echo "$config"
}

# =============================================================================
# CONFIGURATION FILE MANAGEMENT
# =============================================================================

# Write configuration to file
write_config_file() {
    local config="$1"
    local config_file="${2:-$MAVLINK_ROUTER_CONFIG_FILE}"

    # Ensure directory exists
    ma_ensure_dir "$(dirname "$config_file")"

    # Backup existing config if present
    if [[ -f "$config_file" ]]; then
        ma_backup_file "$config_file"
    fi

    # Write new config
    echo "$config" > "$config_file"

    if [[ $? -eq 0 ]]; then
        ma_log_success "Configuration written to: $config_file"
        return 0
    else
        ma_log_error "Failed to write configuration to: $config_file"
        return 1
    fi
}

# Write environment file
write_env_file() {
    local uart_device="${1:-}"
    local uart_baud="${2:-}"
    local udp_endpoints="${3:-}"
    local input_type="${4:-uart}"
    local input_address="${5:-}"
    local input_port="${6:-}"

    local env_file="${MAVLINK_ROUTER_ENV_FILE}"

    # Ensure directory exists
    ma_ensure_dir "$(dirname "$env_file")"

    # Write environment file
    cat > "$env_file" <<EOF
# MAVLink Router Environment Configuration
# Generated by mavlink-anywhere v${MAVLINK_ANYWHERE_VERSION}
# Generated at: $(date -Iseconds)

# Input configuration
INPUT_TYPE=${input_type}
UART_DEVICE=${uart_device}
UART_BAUD=${uart_baud}
INPUT_ADDRESS=${input_address}
INPUT_PORT=${input_port}

# Output endpoints
UDP_ENDPOINTS="${udp_endpoints}"
EOF

    if [[ $? -eq 0 ]]; then
        ma_log_success "Environment file written to: $env_file"
        return 0
    else
        ma_log_error "Failed to write environment file"
        return 1
    fi
}

# Read current configuration values from env file
read_current_config() {
    local env_file="${MAVLINK_ROUTER_ENV_FILE}"

    if [[ -f "$env_file" ]]; then
        source "$env_file"
        return 0
    fi

    return 1
}

# Get current UART device from config
get_current_uart_device() {
    if read_current_config 2>/dev/null; then
        echo "${UART_DEVICE:-$DEFAULT_UART_DEVICE}"
    else
        echo "$DEFAULT_UART_DEVICE"
    fi
}

# Get current baud rate from config
get_current_baud_rate() {
    if read_current_config 2>/dev/null; then
        echo "${UART_BAUD:-$DEFAULT_UART_BAUD}"
    else
        echo "$DEFAULT_UART_BAUD"
    fi
}

# Get current endpoints from config
get_current_endpoints() {
    if read_current_config 2>/dev/null; then
        echo "${UDP_ENDPOINTS:-}"
    else
        echo ""
    fi
}

# =============================================================================
# CONFIGURATION VALIDATION
# =============================================================================

# Validate configuration file syntax
validate_config_file() {
    local config_file="${1:-$MAVLINK_ROUTER_CONFIG_FILE}"

    if [[ ! -f "$config_file" ]]; then
        ma_log_error "Configuration file not found: $config_file"
        return 1
    fi

    # Check for required sections
    if ! grep -q "^\[General\]" "$config_file"; then
        ma_log_error "Missing [General] section in config"
        return 1
    fi

    # Check for at least one endpoint
    if ! grep -qE "^\[(Uart|Udp|Tcp)Endpoint" "$config_file"; then
        ma_log_error "No endpoints defined in config"
        return 1
    fi

    ma_log_success "Configuration file syntax valid"
    return 0
}

# Display current configuration
display_current_config() {
    local config_file="${1:-$MAVLINK_ROUTER_CONFIG_FILE}"

    if [[ ! -f "$config_file" ]]; then
        ma_log_warn "No configuration file found at: $config_file"
        return 1
    fi

    ma_print_box "Current MAVLink Router Configuration"
    ma_print_box_line "File: $config_file"
    ma_print_box_line ""

    # Parse and display key settings
    local uart_device uart_baud
    uart_device=$(grep "^Device=" "$config_file" | head -1 | cut -d= -f2)
    uart_baud=$(grep "^Baud=" "$config_file" | head -1 | cut -d= -f2)

    if [[ -n "$uart_device" ]]; then
        ma_print_box_line "UART Input:"
        ma_print_box_line "  Device: $uart_device"
        ma_print_box_line "  Baud:   $uart_baud"
    fi

    # Count and list UDP endpoints
    local udp_count
    udp_count=$(grep -c "^\[UdpEndpoint" "$config_file" 2>/dev/null || echo "0")

    ma_print_box_line ""
    ma_print_box_line "UDP Endpoints: $udp_count"

    # List endpoints
    while IFS= read -r line; do
        if [[ "$line" =~ ^\[UdpEndpoint\ (.+)\] ]]; then
            local name="${BASH_REMATCH[1]}"
            local addr port mode
            # Read next few lines for details
            read -r addr_line
            read -r port_line
            addr=$(echo "$addr_line" | grep "Address=" | cut -d= -f2)
            port=$(echo "$port_line" | grep "Port=" | cut -d= -f2)
            mode=$(grep "Mode=" <<< "$addr_line$port_line" | cut -d= -f2)
            [[ -z "$mode" ]] && mode="normal"

            ma_print_box_line "  - $name: $addr:$port ($mode)"
        fi
    done < "$config_file"

    ma_print_box_line ""
    ma_print_box_end
}

# =============================================================================
# HIGH-LEVEL CONFIGURATION FUNCTIONS
# =============================================================================

# Configure mavlink-router with UART input (headless)
configure_uart_headless() {
    local uart_device="$1"
    local uart_baud="$2"
    local endpoints="$3"

    ma_log_step "Generating UART configuration..."

    # Validate inputs
    if [[ -z "$uart_device" ]] || [[ -z "$uart_baud" ]] || [[ -z "$endpoints" ]]; then
        ma_log_error "Missing required parameters for headless configuration"
        return 1
    fi

    # Generate config
    local config
    config=$(generate_uart_config "$uart_device" "$uart_baud" "$endpoints")

    # Write config file
    write_config_file "$config" || return 1

    # Write env file
    write_env_file "$uart_device" "$uart_baud" "$endpoints" "uart" || return 1

    ma_log_success "UART configuration complete"
    return 0
}

# Configure mavlink-router with UDP input (headless)
configure_udp_headless() {
    local input_address="$1"
    local input_port="$2"
    local endpoints="$3"

    ma_log_step "Generating UDP input configuration..."

    # Validate inputs
    if [[ -z "$input_address" ]] || [[ -z "$input_port" ]] || [[ -z "$endpoints" ]]; then
        ma_log_error "Missing required parameters for UDP configuration"
        return 1
    fi

    # Generate config
    local config
    config=$(generate_udp_input_config "$input_address" "$input_port" "$endpoints")

    # Write config file
    write_config_file "$config" || return 1

    # Write env file
    write_env_file "" "" "$endpoints" "udp" "$input_address" "$input_port" || return 1

    ma_log_success "UDP input configuration complete"
    return 0
}
